version: "3.9"

services:
  backend:
    image: ghcr.io/sina-morshedi/kheyr-backend:b001b6d7d6dedca0004b52adad08ea1791695e47
    container_name: kheyr-backend
    restart: unless-stopped
    ports:
      - "8088:4000"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATA_MONGODB_URI: mongodb://root:83407899_Sina@194.5.159.251:27017/KheyrApp?authSource=admin
      SERVER_PORT: 4000
      FIREBASE_ENABLED: "true"
      FIREBASE_SERVICE_ACCOUNT_FILE: /app/config/firebase-service-account.json
    volumes:
      - /opt/portainer-stacks/kheyr-backend/secrets/firebase-service-account.json:/app/config/firebase-service-account.json:ro
    networks:
      - nanoelectronics-network

networks:
  nanoelectronics-network:
    external: true
