version: "3.9"

services:
  backend:
    image: ghcr.io/sina-morshedi/kheyr-backend:d15dcd876c60bb2412034ca99925ed8b3e48dd19
    container_name: kheyr-backend
    restart: unless-stopped
    ports:
      - "8088:4000"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATA_MONGODB_URI: ${SPRING_DATA_MONGODB_URI}
      SERVER_PORT: 4000
    volumes:
      - /opt/portainer-stacks/kheyr-backend/secrets/firebase-service-account.json:/app/config/firebase-service-account.json:ro
    networks:
      - nanoelectronics-network

networks:
  nanoelectronics-network:
    external: true
